added a method to send messages to the queue
peak-ai/ais-service-discovery-python pull request #4
Opened 2021-04-12 05:25 UTC by safwan-1998

## Description

This PR adds a method to send messages to the `SQS` queue using service discovery call.

## Review Checks

Please check if the PR fulfills these requirements:

_Put an `x` in the boxes that apply, Remove any lines that do not apply_
- [ ] 📝 The commit message is clear and descriptive
- [ ] 🔐 The Security Considerations section in the PR description is complete - **Please do not remove this**
- [ ] ✅ Tests for the changes have been added and run successfully including the new changes
- [ ] 📄 Documentation has been added / updated (for bug fixes / features)

## Dependencies
N/A

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
- [ ] Yes
- [x] No 

## Security Considerations

Are there any other security or data concerns to be aware of?

Please discuss the security implications/considerations relevant to the proposed change. 
This may include...
* security-relevant design decisions
* concerns 
* important discussions
* implementation-specific guidance and pitfalls
* an outline of threats and risks and how they are being addressed.

## Types of change

What kind of change does this Pull Request introduce?
_Put an `x` in the boxes that apply_

- [ ] 🐛 Bugfix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 Adding or updating configuration files, development scripts etc.
- [ ] ♻️ Refactoring (no functional changes, no api changes)
- [ ] 🧹 Chore (removing redunant files, fixing typos etc.)
- [ ] 📄 Documentation Update 
- [ ] ❓ Other (if none of the other choices apply)

# Testing

`pip install ais_service_discovery`

### send message using service discovery.

    namespace = ''
    service = ''
    handler = '' 
    payload = {}

    response=call(namespace, service, handler, payload)

#### Response 

    {
       "MD5OfMessageBody":"be50fd7811bf19f50bfe3d4d4936aeea",
       "MessageId":"9877e79a-1e61-4d37-ac55-51f51e227006",
       "ResponseMetadata":{
          "RequestId":"93f0eba1-1a74-592c-9355-b34cc1466a60",
          "HTTPStatusCode":200,
          "HTTPHeaders":{
             "x-amzn-requestid":"93f0eba1-1a74-592c-9355-b34cc1466a60",
             "date":"Mon, 12 Apr 2021 05:21:54 GMT",
             "content-type":"text/xml",
             "content-length":"378"
          },
          "RetryAttempts":0
       }
    }

2021-04-12 07:41 UTC, rickihastings approved these changes

2021-04-12 08:58 UTC, EwanValentine approved these changes

2021-04-12 10:59 UTC, azhar22k commented on ais_service_discovery/call_service.py
> +    if type in ['queue']:
Can you update to work on both `queue` and `sqs` keyword just like the [JS lib](https://github.com/peak-ai/ais-service-discovery-js/blob/master/src/call-service.js#L62-L63)

2021-04-12 11:01 UTC, azhar22k requested changes
Thanks for your contribution @safwan-1998 
Few things
1. Added a minor comment for consistency
2. Can you also update the readme to reflect the same (currently it says TODO)

2021-04-13 09:22 UTC, azhar22k commented on README.md
> +- SQS (`send`).
```suggestion
- SQS (`queue`).

```

2021-04-13 09:23 UTC, azhar22k approved these changes

2021-04-13 09:31 UTC, merged